import { StyleSheet } from "react-native";

export const PALETTE = {
  screen: "#F6EFDF",
  screenGlow: "#FBF7EE",
  card: "#FFFFFF",
  tile: "#F4ECD8",
  line: "#D8C8A5",
  ink: "#111111",
  muted: "#3F3527",
  dim: "#776A57",
  gold: "#D8AF47",
  goldDeep: "#C79A2E",
  goldSoft: "#F2E0A8",
  shadow: "rgba(120, 86, 26, 0.16)",
  outline: "#5E4B31",
  badge: "#F4E6B9",
  success: "#5E8B43",
  danger: "#B53B30",
} as const;

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: PALETTE.screen,
  },
  content: {
    paddingHorizontal: 18,
    paddingBottom: 34,
    paddingTop: 8,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 18,
  },
  backButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: PALETTE.gold,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: PALETTE.shadow,
    shadowOpacity: 1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  title: {
    flex: 1,
    fontSize: 28,
    fontWeight: "900",
    color: PALETTE.ink,
  },
  featureCard: {
    backgroundColor: PALETTE.card,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: PALETTE.line,
    padding: 16,
    marginBottom: 14,
    flexDirection: "row",
    gap: 16,
    shadowColor: PALETTE.shadow,
    shadowOpacity: 1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  iconTile: {
    width: 86,
    height: 86,
    borderRadius: 20,
    backgroundColor: PALETTE.tile,
    alignItems: "center",
    justifyContent: "center",
  },
  featureBody: {
    flex: 1,
  },
  featureTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: PALETTE.ink,
    marginBottom: 4,
  },
  featureSub: {
    fontSize: 13,
    lineHeight: 18,
    color: PALETTE.muted,
    marginBottom: 12,
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: 27,
    backgroundColor: PALETTE.gold,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    shadowColor: PALETTE.shadow,
    shadowOpacity: 0.8,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  primaryButtonDisabled: {
    opacity: 0.45,
  },
  primaryButtonText: {
    fontSize: 17,
    fontWeight: "900",
    color: PALETTE.ink,
  },
  reportTypeRow: {
    gap: 8,
    paddingBottom: 6,
  },
  reportTypePill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: PALETTE.line,
    backgroundColor: PALETTE.screenGlow,
  },
  reportTypePillActive: {
    backgroundColor: PALETTE.badge,
    borderColor: PALETTE.goldDeep,
  },
  reportTypeText: {
    fontSize: 12,
    fontWeight: "800",
    color: PALETTE.dim,
  },
  reportTypeTextActive: {
    color: PALETTE.ink,
  },
  secondaryButtonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  outlineButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 26,
    borderWidth: 2,
    borderColor: PALETTE.outline,
    backgroundColor: PALETTE.screenGlow,
    alignItems: "center",
    justifyContent: "center",
  },
  outlineButtonText: {
    fontSize: 16,
    fontWeight: "900",
    color: PALETTE.ink,
  },
  reportStatus: {
    marginTop: 10,
    fontSize: 12,
    lineHeight: 18,
    color: PALETTE.dim,
  },
  insightPreview: {
    marginTop: 10,
    padding: 12,
    borderRadius: 16,
    backgroundColor: PALETTE.screenGlow,
    borderWidth: 1,
    borderColor: PALETTE.line,
  },
  insightPreviewTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: PALETTE.goldDeep,
    marginBottom: 4,
  },
  insightPreviewText: {
    fontSize: 12,
    lineHeight: 18,
    color: PALETTE.muted,
  },
  schemeCard: {
    backgroundColor: PALETTE.card,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: PALETTE.line,
    padding: 16,
    marginBottom: 22,
    shadowColor: PALETTE.shadow,
    shadowOpacity: 1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  schemeHeaderRow: {
    flexDirection: "row",
    gap: 16,
  },
  schemeSeal: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 1.5,
    borderColor: PALETTE.line,
    backgroundColor: "#FFFDF7",
    alignItems: "center",
    justifyContent: "center",
  },
  schemeSealTop: {
    fontSize: 10,
    fontWeight: "900",
    color: PALETTE.dim,
    letterSpacing: 0.6,
  },
  schemeSealBottom: {
    fontSize: 16,
    fontWeight: "900",
    color: PALETTE.ink,
    marginTop: 2,
  },
  schemeBody: {
    flex: 1,
  },
  schemeLine: {
    fontSize: 13,
    lineHeight: 19,
    color: PALETTE.muted,
    marginBottom: 2,
  },
  schemeHint: {
    fontSize: 12,
    lineHeight: 18,
    color: PALETTE.dim,
    marginBottom: 10,
  },
  sectionHeading: {
    fontSize: 26,
    fontWeight: "900",
    color: PALETTE.ink,
    marginBottom: 14,
  },
  consultRow: {
    flexDirection: "row",
    gap: 12,
  },
  consultCard: {
    flex: 1,
    backgroundColor: PALETTE.card,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: PALETTE.line,
    padding: 16,
    minHeight: 250,
    shadowColor: PALETTE.shadow,
    shadowOpacity: 1,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  consultTitle: {
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900",
    color: PALETTE.ink,
    marginTop: 12,
    marginBottom: 10,
  },
  consultCopy: {
    fontSize: 12,
    lineHeight: 18,
    color: PALETTE.muted,
    marginBottom: 16,
  },
  consultUnavailable: {
    fontSize: 12,
    lineHeight: 18,
    color: PALETTE.dim,
    marginTop: 8,
    marginBottom: 16,
  },
  providerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
    marginBottom: 18,
  },
  providerBadge: {
    minWidth: 58,
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  providerBadgeMono: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: "#FFFDF7",
    borderWidth: 1,
    borderColor: PALETTE.line,
  },
  providerBadgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: PALETTE.ink,
    textAlign: "center",
  },
  providerBadgeTextMono: {
    fontSize: 12,
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: "rgba(17, 17, 17, 0.28)",
    justifyContent: "flex-end",
  },
  sheetWrap: {
    backgroundColor: PALETTE.screenGlow,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 10,
    maxHeight: "82%",
  },
  sheetHandle: {
    alignSelf: "center",
    width: 54,
    height: 5,
    borderRadius: 999,
    backgroundColor: PALETTE.line,
    marginBottom: 12,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  sheetTitle: {
    fontSize: 21,
    fontWeight: "900",
    color: PALETTE.ink,
  },
  sheetClose: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PALETTE.card,
  },
  sheetContent: {
    paddingHorizontal: 18,
    paddingBottom: 30,
    gap: 12,
  },
  sheetLoader: {
    marginTop: 24,
  },
  sheetCard: {
    backgroundColor: PALETTE.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PALETTE.line,
    padding: 14,
  },
  sheetCardTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: PALETTE.ink,
    marginBottom: 4,
  },
  sheetCardMeta: {
    fontSize: 11,
    fontWeight: "800",
    color: PALETTE.goldDeep,
    marginBottom: 4,
  },
  sheetCardCopy: {
    fontSize: 12,
    lineHeight: 18,
    color: PALETTE.muted,
  },
  analysisCard: {
    backgroundColor: PALETTE.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: PALETTE.line,
    padding: 16,
  },
  analysisHeading: {
    fontSize: 14,
    fontWeight: "900",
    color: PALETTE.ink,
    marginBottom: 6,
    marginTop: 12,
  },
  analysisCopy: {
    fontSize: 12,
    lineHeight: 18,
    color: PALETTE.muted,
  },
  analysisDisclaimer: {
    marginTop: 16,
    fontSize: 11,
    lineHeight: 16,
    color: PALETTE.dim,
  },
  sheetEmpty: {
    fontSize: 13,
    lineHeight: 19,
    color: PALETTE.muted,
  },
  bulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 6,
  },
  bulletDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: PALETTE.goldDeep,
    marginTop: 5,
  },
  bulletText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: PALETTE.muted,
  },
});
