export const ruralPalette = {
  bg: "#F7F1E6",
  bgWarm: "#F3EAD7",
  surface: "#FCFBF7",
  surfaceSoft: "#F8F3E8",
  white: "#FFFFFF",
  line: "#E8DDC7",
  lineSoft: "#EFE6D6",
  ink: "#252139",
  muted: "#A39B8F",
  mutedDark: "#6E675E",
  gold: "#E9C768",
  goldDark: "#C99B35",
  goldSoft: "#F5E4AE",
  goldTint: "rgba(233,199,104,0.22)",
  goldShadow: "rgba(201,155,53,0.28)",
  chipBlue: "#4C8DF6",
  chipBlueDark: "#2F71DA",
  tabInactive: "#B8B0A7",
  health: "#CDE8BC",
  healthIcon: "#88B178",
  knowledge: "#E0C8F5",
  knowledgeIcon: "#AE79DB",
  infra: "#C8ECEB",
  infraIcon: "#73B8B2",
  economics: "#D6E1FF",
  economicsIcon: "#7088D6",
  agriculture: "#F6E3A6",
  agricultureIcon: "#CFAB45",
};

export const askDomains = [
  {
    key: "agriculture",
    label: "Agriculture",
    icon: "leaf",
    bubble: ruralPalette.agriculture,
    iconColor: ruralPalette.agricultureIcon,
  },
  {
    key: "health",
    label: "Health",
    icon: "heart",
    bubble: ruralPalette.health,
    iconColor: ruralPalette.healthIcon,
  },
  {
    key: "knowledge",
    label: "Knowledge",
    icon: "school",
    bubble: ruralPalette.knowledge,
    iconColor: ruralPalette.knowledgeIcon,
  },
  {
    key: "infrastructure",
    label: "Infrastructure",
    icon: "business",
    bubble: ruralPalette.infra,
    iconColor: ruralPalette.infraIcon,
  },
  {
    key: "economics",
    label: "Economics",
    icon: "cash",
    bubble: ruralPalette.economics,
    iconColor: ruralPalette.economicsIcon,
  },
] as const;
